spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Test_DB
    username: root
    password: Mp2496431
    driver-class-name: com.mysql.cj.jdbc.Driver

  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'mysql:mysql-connector-java:8.0.30'
  // https://mvnrepository.com/artifact/org.thymeleaf/thymeleaf
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
  
  compileOnly 'org.projectlombok:lombok'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  annotationProcessor 'org.projectlombok:lombok'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  
  
  // https://mvnrepository.com/artifact/mysql/mysql-connector-java
implementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.30'
